const currentUser = JSON.parse(localStorage.getItem("currentUser") || "null");
if(!currentUser || currentUser.role !== "employee") location.href="index.html";
const employeeName=document.getElementById("employeeName"),employeeDepartment=document.getElementById("employeeDepartment"),todayDate=document.getElementById("todayDate"),weekNumber=document.getElementById("weekNumber"),pdfFile=document.getElementById("pdfFile"),selectedFile=document.getElementById("selectedFile"),uploadBtn=document.getElementById("uploadBtn"),uploadText=document.getElementById("uploadText"),reportsTable=document.getElementById("reportsTable"),reportsCount=document.getElementById("reportsCount"),uploadNotice=document.getElementById("uploadNotice"),successCard=document.getElementById("successCard"),uploadCard=document.getElementById("uploadCard"),logoutBtn=document.getElementById("logoutBtn"),statusBadge=document.getElementById("statusBadge");
employeeName.textContent=currentUser.name||"الموظف";employeeDepartment.textContent=currentUser.department||"القسم";
const today=new Date();todayDate.textContent=today.toLocaleDateString("ar-EG",{weekday:"long",year:"numeric",month:"long",day:"numeric"});
function getMonthWeek(date){const months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],weeks=["الأول","الثاني","الثالث","الرابع","الخامس"];const w=Math.ceil(date.getDate()/7);return `الأسبوع ${weeks[w-1]||w} - ${months[date.getMonth()]}`}
weekNumber.textContent=getMonthWeek(today);
logoutBtn.addEventListener("click",()=>{if(typeof showConfirm==="function")showConfirm("هل تريد تسجيل الخروج من النظام؟",()=>{localStorage.removeItem("currentUser");location.href="index.html"},"تسجيل الخروج");else if(confirm("هل تريد تسجيل الخروج؟")){localStorage.removeItem("currentUser");location.href="index.html"}});
pdfFile.addEventListener("change",()=>{const file=pdfFile.files[0];if(!file){selectedFile.textContent="لم يتم اختيار أي ملف";return}if(file.type!=="application/pdf"){showWarning("يسمح فقط بملفات PDF.");pdfFile.value="";selectedFile.textContent="لم يتم اختيار أي ملف";return}selectedFile.innerHTML=`<strong>${escapeHtml(file.name)}</strong><br>${(file.size/1024/1024).toFixed(2)} MB`});
uploadBtn.addEventListener("click",uploadReport);
async function uploadReport(){if(!pdfFile.files.length){showWarning("اختر ملف PDF أولاً.");return}const file=pdfFile.files[0];if(file.type!=="application/pdf"){showWarning("الملف يجب أن يكون بصيغة PDF.");return}uploadBtn.disabled=true;uploadText.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> جارٍ رفع التقرير...';try{const result=await readFile(file);const response=await api("uploadReport",{employeeId:currentUser.id,employeeName:currentUser.name,department:currentUser.department,week:getMonthWeek(new Date()),fileName:file.name,mimeType:file.type,fileData:result});if(response.success){showSuccess("تم رفع التقرير وحفظه بنجاح.");pdfFile.value="";selectedFile.textContent="لم يتم اختيار أي ملف";await loadReports();uploadCard.style.display="none";successCard.style.display="block";setStatus(true)}else showError(response.message||"تعذر رفع التقرير.")}catch(e){showError(e.message||"حدث خطأ أثناء رفع التقرير.")}finally{uploadBtn.disabled=false;uploadText.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i> رفع التقرير'}}
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(",")[1]);r.onerror=reject;r.readAsDataURL(file)})}
async function checkWeeklyReport(){try{const result=await api("checkWeeklyReport",{employeeId:currentUser.id,week:getMonthWeek(new Date())});if(!result.success)return;if(result.uploaded){uploadCard.style.display="none";successCard.style.display="block";setStatus(true)}else setStatus(false)}catch(e){console.warn(e)}}
async function checkUploadPermission(){try{const result=await api("getSettings");if(!result.success)return;const weekly=await api("checkWeeklyReport",{employeeId:currentUser.id,week:getMonthWeek(new Date())});if(weekly.success&&weekly.uploaded){uploadNotice.style.display="none";return}const settings=result.settings,dayNames={0:"الأحد",1:"الإثنين",2:"الثلاثاء",3:"الأربعاء",4:"الخميس",5:"الجمعة",6:"السبت"},now=new Date(),day=String(now.getDay()),time=String(now.getHours()).padStart(2,"0")+":"+String(now.getMinutes()).padStart(2,"0"),start=String(settings.startTime).substring(0,5),end=String(settings.endTime).substring(0,5),allowed=day===String(settings.uploadDay)&&time>=start&&time<=end;if(allowed){uploadNotice.style.display="none";setStatus(false);return}uploadBtn.disabled=true;uploadBtn.innerHTML='<i class="fa-solid fa-lock"></i> رفع التقارير غير متاح';statusBadge.className="welcome-badge locked";statusBadge.innerHTML='<i class="fa-solid fa-lock"></i><span>الرفع مغلق</span>';uploadNotice.style.display="block";uploadNotice.innerHTML=`<h3><i class="fa-solid fa-lock"></i> رفع التقارير مغلق حاليًا</h3><div class="notice-row"><span class="notice-label">يوم الرفع</span><span class="notice-value">${dayNames[settings.uploadDay]}</span></div><div class="notice-row"><span class="notice-label">وقت الرفع</span><span class="notice-value">${formatTime(start)} ← ${formatTime(end)}</span></div><div class="notice-footer">سيتم تفعيل الرفع تلقائيًا عند بداية الموعد المحدد.</div>`}catch(e){console.warn(e)}}
function formatTime(time){let [h,m]=String(time).split(":");h=parseInt(h);const p=h>=12?"م":"ص";h=h%12||12;return `${String(h).padStart(2,"0")}:${m} ${p}`}
async function loadReports(){try{const result=await api("getReports",{employeeId:currentUser.id});if(!result.success){reportsTable.innerHTML='<div class="empty">تعذر تحميل التقارير.</div>';return}const reports=result.reports||[];reportsCount.textContent=reports.length;if(!reports.length){reportsTable.innerHTML='<div class="empty"><i class="fa-regular fa-folder-open" style="font-size:28px;display:block;margin-bottom:8px"></i>لا توجد تقارير سابقة حتى الآن.</div>';return}reportsTable.innerHTML=reports.map(report=>{const d=new Date(report.uploadDate),date=d.toLocaleString("ar-EG",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:true}),title=escapeHtml(report.week||"التقرير الأسبوعي"),file=escapeHtml(report.fileName||"ملف التقرير.pdf"),url=escapeAttr(report.url||"");return `<div class="report-item"><div class="report-main"><div class="report-title"><i class="fa-solid fa-file-pdf"></i>${title}</div><div class="report-meta">${file} • ${date}</div></div><a href="${url}" class="view-btn" data-report-title="${escapeAttr(report.week||"التقرير الأسبوعي")}"><i class="fa-solid fa-eye"></i> عرض التقرير</a></div>`}).join("")}catch(e){reportsTable.innerHTML='<div class="empty">تعذر تحميل التقارير.</div>'}}
function openEmployeePdf(url,title){if(!url)return showError("رابط التقرير غير متاح.");const modal=document.getElementById("employeePdfModal"),frame=document.getElementById("employeePdfFrame"),loading=document.getElementById("employeePdfLoading");document.getElementById("employeePdfTitle").textContent=title||"التقرير الأسبوعي";loading.classList.remove("hide");frame.src=url;frame.dataset.url=url;modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";frame.onload=()=>loading.classList.add("hide")}
function closeEmployeePdf(){const modal=document.getElementById("employeePdfModal");modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.style.overflow="";setTimeout(()=>document.getElementById("employeePdfFrame").src="about:blank",180)}
document.addEventListener("click",e=>{const link=e.target.closest("a.view-btn");if(!link)return;e.preventDefault();openEmployeePdf(link.getAttribute("href"),link.dataset.reportTitle||"التقرير الأسبوعي")});document.getElementById("employeePdfClose").onclick=closeEmployeePdf;document.getElementById("employeePdfExternal").onclick=()=>{const u=document.getElementById("employeePdfFrame").dataset.url;if(u)window.open(u,"_blank","noopener")};document.getElementById("employeePdfModal").addEventListener("click",e=>{if(e.target.id==="employeePdfModal")closeEmployeePdf()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeEmployeePdf()});
function setStatus(uploaded){if(!statusBadge)return;if(uploaded){statusBadge.className="welcome-badge";statusBadge.innerHTML='<i class="fa-solid fa-circle-check"></i><span>تم رفع تقرير هذا الأسبوع</span>'}else{statusBadge.className="welcome-badge";statusBadge.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i><span>بانتظار التقرير</span>'}}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function escapeAttr(v){return escapeHtml(v)}
checkWeeklyReport();checkUploadPermission();loadReports();
