const currentUser=JSON.parse(localStorage.getItem("currentUser")||"null");
if(!currentUser||currentUser.role!=="employee")location.href="index.html";
const $=id=>document.getElementById(id);let allReports=[];
const nameEl=$("employeeName"),deptEl=$("employeeDepartment"),dateEl=$("todayDate"),weekEl=$("weekNumber"),fileEl=$("pdfFile"),selectedEl=$("selectedFile"),uploadEl=$("uploadBtn"),uploadText=$("uploadText"),reportsEl=$("reportsTable"),countEl=$("reportsCount"),totalEl=$("reportsTotal"),weekStatusEl=$("weekStatus"),lastUploadEl=$("lastUpload"),noticeEl=$("uploadNotice"),successEl=$("successCard"),cardEl=$("uploadCard"),statusEl=$("statusBadge"),dropzone=$("uploadDropzone"),searchEl=$("reportsSearch"),filterEl=$("reportsFilter"),refreshEl=$("refreshBtn");
nameEl.textContent=currentUser.name||"الموظف";deptEl.textContent=currentUser.department||"القسم";
const today=new Date();
function getMonthWeek(d){const months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],weeks=["الأول","الثاني","الثالث","الرابع","الخامس"];return `الأسبوع ${weeks[Math.ceil(d.getDate()/7)-1]||Math.ceil(d.getDate()/7)} - ${months[d.getMonth()]}`}
weekEl.textContent=getMonthWeek(today);
function setUploadSchedule(settings){if(!settings)return;const days={0:"الأحد",1:"الإثنين",2:"الثلاثاء",3:"الأربعاء",4:"الخميس",5:"الجمعة",6:"السبت"};const day=days[Number(settings.uploadDay)]||"الخميس",start=String(settings.startTime||"").substring(0,5),end=String(settings.endTime||"").substring(0,5);dateEl.innerHTML=`<span>موعد الرفع: ${day}</span><small>${start&&end?`${formatTime(start)} ← ${formatTime(end)}`:"حسب الموعد المحدد"}</small>`}
$("logoutBtn").addEventListener("click",()=>{const out=()=>{localStorage.removeItem("currentUser");location.href="index.html"};if(typeof showConfirm==="function")showConfirm("هل تريد تسجيل الخروج من النظام؟",out,"تسجيل الخروج");else if(confirm("هل تريد تسجيل الخروج؟"))out()});
refreshEl?.addEventListener("click",async()=>{refreshEl.classList.add("is-loading");try{await Promise.all([checkWeeklyReport(),checkUploadPermission(),loadReports()])}finally{setTimeout(()=>refreshEl.classList.remove("is-loading"),350)}});
function validFile(file){if(!file)return false;if(file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf")){showWarning("يسمح فقط بملفات PDF.");fileEl.value="";selectedEl.textContent="لم يتم اختيار أي ملف";return false}selectedEl.innerHTML=`<i class="fa-solid fa-file-pdf"></i><span><strong>${escapeHtml(file.name)}</strong><small>${(file.size/1048576).toFixed(2)} MB</small></span><i class="fa-solid fa-circle-check file-ok"></i>`;selectedEl.classList.add("has-file");return true}
fileEl.addEventListener("change",()=>validFile(fileEl.files[0]));
["dragenter","dragover"].forEach(x=>dropzone?.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add("dragging")}));["dragleave","drop"].forEach(x=>dropzone?.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove("dragging")}));
dropzone?.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(!f)return;const dt=new DataTransfer();dt.items.add(f);fileEl.files=dt.files;validFile(f)});
uploadEl.addEventListener("click",uploadReport);
async function uploadReport(){const file=fileEl.files[0];if(!file){showWarning("اختر ملف PDF أولاً.");return}if(!validFile(file))return;uploadEl.disabled=true;uploadText.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> جارٍ رفع التقرير...';try{const data=await readFile(file),res=await api("uploadReport",{employeeId:currentUser.id,employeeName:currentUser.name,department:currentUser.department,week:getMonthWeek(new Date()),fileName:file.name,mimeType:file.type||"application/pdf",fileData:data});if(res.success){showSuccess("تم رفع التقرير وحفظه بنجاح.");fileEl.value="";selectedEl.textContent="لم يتم اختيار أي ملف";selectedEl.classList.remove("has-file");await loadReports();showUploadedState()}else showError(res.message||"تعذر رفع التقرير.")}catch(e){showError(e.message||"حدث خطأ أثناء رفع التقرير")}finally{uploadEl.disabled=false;uploadText.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i> رفع التقرير'}}
function showUploadedState(){cardEl.style.display="none";successEl.style.display="flex";setStatus(true)}
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(",")[1]);r.onerror=reject;r.readAsDataURL(file)})}
async function checkWeeklyReport(){try{const r=await api("checkWeeklyReport",{employeeId:currentUser.id,week:getMonthWeek(new Date())});if(!r.success)return;if(r.uploaded)showUploadedState();else{setStatus(false);cardEl.style.display="block";successEl.style.display="none"}}catch(e){console.warn(e)}}
async function checkUploadPermission(){try{const r=await api("getSettings");if(!r.success)return;setUploadSchedule(r.settings);const w=await api("checkWeeklyReport",{employeeId:currentUser.id,week:getMonthWeek(new Date())});if(w.success&&w.uploaded){noticeEl.style.display="none";return}const s=r.settings,days={0:"الأحد",1:"الإثنين",2:"الثلاثاء",3:"الأربعاء",4:"الخميس",5:"الجمعة",6:"السبت"},n=new Date(),day=String(n.getDay()),time=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0"),start=String(s.startTime).substring(0,5),end=String(s.endTime).substring(0,5),allowed=day===String(s.uploadDay)&&time>=start&&time<=end;if(allowed){noticeEl.style.display="none";uploadEl.disabled=false;uploadText.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i> رفع التقرير';setStatus(false);return}uploadEl.disabled=true;uploadEl.innerHTML='<i class="fa-solid fa-lock"></i> رفع التقارير غير متاح';statusEl.className="welcome-badge locked";statusEl.innerHTML='<i class="fa-solid fa-lock"></i><span>الرفع مغلق</span>';weekStatusEl.textContent="الرفع مغلق";noticeEl.style.display="block";noticeEl.innerHTML=`<h3><i class="fa-solid fa-lock"></i> رفع التقارير مغلق حاليًا</h3><div class="notice-row"><span class="notice-label">يوم الرفع</span><span class="notice-value">${days[s.uploadDay]}</span></div><div class="notice-row"><span class="notice-label">وقت الرفع</span><span class="notice-value">${formatTime(start)} ← ${formatTime(end)}</span></div><div class="notice-footer">سيتم تفعيل الرفع تلقائيًا عند بداية الموعد المحدد.</div>`}catch(e){console.warn(e)}}
function formatTime(t){let[h,m]=String(t).split(":");h=parseInt(h);const p=h>=12?"م":"ص";h=h%12||12;return `${String(h).padStart(2,"0")}:${m} ${p}`}
async function loadReports(){try{const r=await api("getReports",{employeeId:currentUser.id});if(!r.success){reportsEl.innerHTML='<div class="empty">تعذر تحميل التقارير.</div>';return}allReports=r.reports||[];countEl.textContent=allReports.length;totalEl.textContent=allReports.length;updateLast();renderReports()}catch(e){reportsEl.innerHTML='<div class="empty">تعذر تحميل التقارير.</div>'}}
function updateLast(){const dates=allReports.map(x=>new Date(x.uploadDate)).filter(x=>!isNaN(x)).sort((a,b)=>b-a);lastUploadEl.textContent=dates[0]?dates[0].toLocaleDateString("ar-SA",{day:"numeric",month:"short"}):"لا يوجد"}
function renderReports(){let list=[...allReports],q=(searchEl?.value||"").trim().toLowerCase(),mode=filterEl?.value||"all";if(q)list=list.filter(x=>`${x.week||""} ${x.fileName||""}`.toLowerCase().includes(q));list.sort((a,b)=>{const x=new Date(a.uploadDate),y=new Date(b.uploadDate);return mode==="oldest"?x-y:y-x});if(!list.length){reportsEl.innerHTML=`<div class="empty"><i class="fa-regular fa-folder-open"></i>${allReports.length?"لا توجد نتائج مطابقة لبحثك.":"لا توجد تقارير سابقة حتى الآن."}</div>`;return}reportsEl.innerHTML=list.map(r=>{const d=new Date(r.uploadDate),date=isNaN(d)?"تاريخ غير متاح":d.toLocaleString("ar-SA",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:true}),title=escapeHtml(r.week||"التقرير الأسبوعي"),file=escapeHtml(r.fileName||"ملف التقرير.pdf"),url=escapeAttr(r.url||"");return `<div class="report-item"><div class="report-main"><div class="report-title"><span class="report-file-icon"><i class="fa-solid fa-file-pdf"></i></span><span>${title}</span></div><div class="report-meta"><i class="fa-regular fa-file"></i> ${file}<span>•</span><i class="fa-regular fa-clock"></i> ${date}</div></div><a href="${url}" class="view-btn" data-report-title="${escapeAttr(r.week||"التقرير الأسبوعي")}"><i class="fa-solid fa-eye"></i><span>عرض التقرير</span></a></div>`}).join("")}
searchEl?.addEventListener("input",renderReports);filterEl?.addEventListener("change",renderReports);
function openEmployeePdf(url,title){if(!url)return showError("رابط التقرير غير متاح.");const modal=$("employeePdfModal"),frame=$("employeePdfFrame"),loading=$("employeePdfLoading");$("employeePdfTitle").textContent=title||"التقرير الأسبوعي";loading.classList.remove("hide");frame.src=url;frame.dataset.url=url;modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";frame.onload=()=>loading.classList.add("hide")}
function closeEmployeePdf(){const modal=$("employeePdfModal");modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.style.overflow="";setTimeout(()=>$("employeePdfFrame").src="about:blank",180)}
document.addEventListener("click",e=>{const a=e.target.closest("a.view-btn");if(!a)return;e.preventDefault();openEmployeePdf(a.getAttribute("href"),a.dataset.reportTitle||"التقرير الأسبوعي")});$("employeePdfClose").onclick=closeEmployeePdf;$("employeePdfExternal").onclick=()=>{const u=$("employeePdfFrame").dataset.url;if(u)window.open(u,"_blank","noopener")};$("employeePdfModal").addEventListener("click",e=>{if(e.target.id==="employeePdfModal")closeEmployeePdf()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeEmployeePdf()});
function setStatus(uploaded){if(uploaded){statusEl.className="welcome-badge";statusEl.innerHTML='<i class="fa-solid fa-circle-check"></i><span>تم رفع تقرير هذا الأسبوع</span>';weekStatusEl.textContent="تم الرفع"}else{statusEl.className="welcome-badge";statusEl.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i><span>بانتظار التقرير</span>';weekStatusEl.textContent="بانتظار الرفع"}}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function escapeAttr(v){return escapeHtml(v)}
checkWeeklyReport();checkUploadPermission();loadReports();
